# Generated by Django 4.2.24 on 2025-09-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('status_ha', models.FloatField(blank=True, null=True)),
                ('status_percent', models.FloatField(blank=True, null=True)),
                ('ziel_ha', models.FloatField(blank=True, null=True)),
                ('ziel_percent', models.FloatField(blank=True, null=True)),
                ('change_ratio', models.FloatField(blank=True, null=True)),
                ('quelle', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
