# Generated by Django 4.2.24 on 2025-09-28 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landuse',
            options={'ordering': ['code']},
        ),
        migrations.RenameField(
            model_name='landuse',
            old_name='change_ratio',
            new_name='target_ha',
        ),
        migrations.RemoveField(
            model_name='landuse',
            name='status_percent',
        ),
        migrations.RemoveField(
            model_name='landuse',
            name='ziel_ha',
        ),
        migrations.RemoveField(
            model_name='landuse',
            name='ziel_percent',
        ),
        migrations.AddField(
            model_name='landuse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='simulator.landuse'),
        ),
    ]
