# Generated by Django 4.2.24 on 2025-09-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_landuse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='change_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landuse',
            name='status_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landuse',
            name='target_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
