# Generated by Django 4.2.24 on 2025-09-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_landuse_change_ratio_landuse_status_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landuse',
            name='change_ratio',
        ),
        migrations.RemoveField(
            model_name='landuse',
            name='status_percent',
        ),
        migrations.RemoveField(
            model_name='landuse',
            name='target_percent',
        ),
    ]
