# Generated by Django 4.2.24 on 2025-09-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_remove_landuse_change_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landuse',
            name='user_percent',
            field=models.FloatField(blank=True, help_text='User-defined percentage for target calculation', null=True),
        ),
    ]
