# Generated by Django 4.2.24 on 2025-09-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_landuse_user_percent'),
    ]

    operations = [
    ]
