# Generated by Django 4.2.24 on 2025-09-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_auto_20250928_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('status_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('user_input', models.FloatField(blank=True, null=True)),
                ('formula', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'subcategory', 'code', 'name'],
                'indexes': [models.Index(fields=['category'], name='simulator_r_categor_ddff3d_idx'), models.Index(fields=['category', 'subcategory'], name='simulator_r_categor_0867d7_idx')],
            },
        ),
    ]
