# Generated by Django 4.2.24 on 2025-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_renewabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewabledata',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='renewabledata',
            name='parent_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
