# Generated by Django 4.2.23 on 2025-10-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_renewabledata_is_fixed_renewabledata_parent_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbrauchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=20)),
                ('status', models.FloatField(blank=True, null=True)),
                ('ziel', models.FloatField(blank=True, null=True)),
                ('user_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='simulator_v_code_af60ee_idx')],
            },
        ),
    ]
