# Generated by Django 4.2.23 on 2025-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0010_auto_20251021_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbrauchdata',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
