# Generated by Django 4.2.23 on 2025-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_verbrauchdata_is_calculated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GebaeudewaermeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=30)),
                ('status', models.FloatField(blank=True, null=True)),
                ('ziel', models.FloatField(blank=True, null=True)),
                ('formula', models.CharField(blank=True, max_length=100, null=True)),
                ('is_calculated', models.BooleanField(default=False)),
                ('user_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='simulator_g_code_ec4358_idx')],
            },
        ),
    ]
