# Generated by Django 4.2.23 on 2025-10-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_gebaeudewaermedata'),
    ]

    operations = [
    ]
