# Generated by Django 4.2.23 on 2025-10-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0013_auto_20251021_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landuse',
            name='user_percent',
            field=models.FloatField(blank=True, help_text='User-defined percentage for target calculations', null=True),
        ),
    ]
