# Generated by Django 4.2.23 on 2025-10-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0014_alter_landuse_user_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebaeudewaermedata',
            name='status_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gebaeudewaermedata',
            name='ziel_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verbrauchdata',
            name='status_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verbrauchdata',
            name='ziel_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
