# Generated by Django 4.2.23 on 2025-11-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_gebaeudewaermedata_status_calculated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_im_jahr', models.IntegerField(help_text='Tag im Jahr (Day in Year)')),
                ('datum_ref', models.CharField(help_text='Datum Ref.', max_length=20)),
                ('wind_promille', models.FloatField(blank=True, help_text='Wind Promille', null=True)),
                ('solar_promille', models.FloatField(blank=True, help_text='Solar Promille', null=True)),
                ('heizung_abwaerm_promille', models.FloatField(blank=True, help_text='Heizung Abwärm. Promille', null=True)),
                ('verbrauch_promille', models.FloatField(blank=True, help_text='Verbrauch Promille', null=True)),
                ('stromverbr', models.FloatField(blank=True, help_text='Stromverbr.', null=True)),
                ('kavon', models.FloatField(blank=True, help_text='Kavon', null=True)),
                ('raumwaerm_korr', models.FloatField(blank=True, help_text='Raumwärm.Korr.', null=True)),
                ('stromverbr_raumwaerm_korr', models.FloatField(blank=True, help_text='Stromverbr. Raumwärm.Korr.', null=True)),
                ('windstrom', models.FloatField(blank=True, help_text='Windstrom', null=True)),
                ('solarstrom', models.FloatField(blank=True, help_text='Solarstrom', null=True)),
                ('sonst_kraft_konstant', models.FloatField(blank=True, help_text='Sonst.Kraft(konstant)', null=True)),
                ('wind_solar_konstant', models.FloatField(blank=True, help_text='Wind+Solar Konstant', null=True)),
                ('direktverbr_strom', models.FloatField(blank=True, help_text='Direktverbr. Strom', null=True)),
                ('ueberschuss_strom', models.FloatField(blank=True, help_text='Überschuss Strom', null=True)),
                ('entsteht', models.FloatField(blank=True, help_text='Entsteht.', null=True)),
                ('abgeltung', models.FloatField(blank=True, help_text='Abgeltung', null=True)),
                ('mangel_last', models.FloatField(blank=True, help_text='Mangel-Last', null=True)),
                ('brennstoff_ausgleichs_strom', models.FloatField(blank=True, help_text='Brennstoff-Ausgleichs-Strom', null=True)),
                ('speicher_ausgl_strom', models.FloatField(blank=True, help_text='Speicher-Ausgl.+ Strom', null=True)),
                ('aussprech_rueckwaerts', models.FloatField(blank=True, help_text='Aussprech. Rückwärts.', null=True)),
                ('aussprech_gas', models.FloatField(blank=True, help_text='Aussprech. Gas', null=True)),
                ('ladeabst_bunto', models.FloatField(blank=True, help_text='Ladeabst. Bunto', null=True)),
                ('ladeabbstand_last_vom_tl', models.FloatField(blank=True, help_text='Ladeabbstand Last vom TL', null=True)),
                ('selbstentl', models.FloatField(blank=True, help_text='Selbstentl.', null=True)),
                ('ladeabbzustan_ladezust', models.FloatField(blank=True, help_text='Ladeabbzustan Ladezust', null=True)),
                ('netto', models.FloatField(blank=True, help_text='Netto', null=True)),
                ('ladeabbzustan', models.FloatField(blank=True, help_text='Ladeabbzustan', null=True)),
                ('abacadae', models.FloatField(blank=True, help_text='ABACADAE', null=True)),
                ('uebersicht_speich_last', models.FloatField(blank=True, help_text='Übersicht Speich-Last', null=True)),
                ('uebersicht_aussprech', models.FloatField(blank=True, help_text='Übersicht Aussprech.', null=True)),
                ('uebersicht_entspeich', models.FloatField(blank=True, help_text='Übersicht Entspeich.', null=True)),
                ('umrechnun', models.FloatField(blank=True, help_text='Umrechnun', null=True)),
                ('tl_mwh_1y', models.FloatField(blank=True, help_text='TL/MWh*(1Y)', null=True)),
                ('konstanstr_tl', models.FloatField(blank=True, help_text='Konstanstr. (TL)', null=True)),
                ('solarstrom_tl', models.FloatField(blank=True, help_text='Solarstrom (TL)', null=True)),
                ('windstrom_tl', models.FloatField(blank=True, help_text='Windstrom (TL)', null=True)),
                ('solar_konst_tl', models.FloatField(blank=True, help_text='Solar-Konst (TL)', null=True)),
                ('konst_win_solar_tl', models.FloatField(blank=True, help_text='Konst.+Win Solar (TL)', null=True)),
                ('verbrauch_tl', models.FloatField(blank=True, help_text='Verbrauch (TL)', null=True)),
                ('konstantstr', models.FloatField(blank=True, help_text='Konstantstr.', null=True)),
                ('solar_kons_1_tageay', models.FloatField(blank=True, help_text='Solar+Kons (1-TageaY.)', null=True)),
                ('wind_sol_win_tv', models.FloatField(blank=True, help_text='Wind. (Sol+ Win<TV)', null=True)),
                ('unterbedeck', models.FloatField(blank=True, help_text='Unterbedeck.', null=True)),
                ('solar_tv', models.FloatField(blank=True, help_text='Solar (>TV)', null=True)),
                ('wind_tv', models.FloatField(blank=True, help_text='Wind (>TV)', null=True)),
                ('ladeabzustan_d_abs_tl', models.FloatField(blank=True, help_text='Ladeabzustan d.Abs. (TL)', null=True)),
                ('unterbedeck_ohne_wind', models.FloatField(blank=True, help_text='Unterbedeck. Ohne Wind', null=True)),
                ('additional_column_ay', models.FloatField(blank=True, help_text='Column AY', null=True)),
                ('additional_column_az', models.FloatField(blank=True, help_text='Column AZ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WS Data Entry',
                'verbose_name_plural': 'WS Data Entries',
                'ordering': ['tag_im_jahr'],
            },
        ),
    ]
