# Generated by Django 4.2.23 on 2025-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0016_wsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsdata',
            name='kavon',
        ),
        migrations.AddField(
            model_name='wsdata',
            name='davon_raumw_korr',
            field=models.FloatField(blank=True, help_text='davon Raumw.korr.', null=True),
        ),
    ]
