# Generated by Django 4.2.23 on 2025-11-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_remove_wsdata_kavon_wsdata_davon_raumw_korr'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsdata',
            name='einspeich',
            field=models.FloatField(blank=True, help_text='Einspeich', null=True),
        ),
    ]
