# Generated by Django 4.2.23 on 2025-11-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0018_wsdata_einspeich'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsdata',
            name='abregelung',
            field=models.FloatField(blank=True, help_text='Abregelung', null=True),
        ),
    ]
