# Generated by Django 4.2.23 on 2025-11-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0019_wsdata_abregelung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsdata',
            name='abregelung',
        ),
        migrations.AddField(
            model_name='wsdata',
            name='abregelung_z',
            field=models.FloatField(blank=True, help_text='Abregelung.Z', null=True),
        ),
    ]
