# Generated by Django 4.2.23 on 2025-11-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0020_rename_abregelung_to_abregelung_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsdata',
            name='abgeltung',
        ),
        migrations.AlterField(
            model_name='wsdata',
            name='speicher_ausgl_strom',
            field=models.FloatField(blank=True, help_text='Speicher-Ausgl-Strom', null=True),
        ),
    ]
