# Generated by Django 4.2.23 on 2025-11-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0021_remove_wsdata_abgeltung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsdata',
            name='ausspeich_gas',
            field=models.FloatField(blank=True, help_text='Ausspeich. Gas', null=True),
        ),
        migrations.AddField(
            model_name='wsdata',
            name='ausspeich_rueckverstr',
            field=models.FloatField(blank=True, help_text='Ausspeich.Rückverstr.', null=True),
        ),
        migrations.AddField(
            model_name='wsdata',
            name='ladezust_burtto',
            field=models.FloatField(blank=True, help_text='Ladezust.Burtto', null=True),
        ),
        migrations.AddField(
            model_name='wsdata',
            name='ladezustand_abs_vorl_tl',
            field=models.FloatField(blank=True, help_text='LadezustandAbs. vorl.TL', null=True),
        ),
    ]
