# Generated by Django 4.2.23 on 2025-11-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_wsdata_ausspeich_gas_wsdata_ausspeich_rueckverstr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsdata',
            name='ladezustand_netto',
            field=models.FloatField(blank=True, help_text='Ladezustand Netto', null=True),
        ),
    ]
