# Generated by Django 4.2.23 on 2025-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0023_wsdata_ladezustand_netto'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsdata',
            name='ladezustand_abs',
            field=models.FloatField(blank=True, help_text='Ladezustand Abs.', null=True),
        ),
    ]
