# Generated by Django 4.2.24 on 2025-12-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0027_formula_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula',
            options={'ordering': ['category', 'key'], 'verbose_name': 'Formula', 'verbose_name_plural': 'Formulas'},
        ),
        migrations.AlterModelOptions(
            name='formulavariable',
            options={'ordering': ['formula__key', 'variable_name'], 'verbose_name': 'Formula Variable', 'verbose_name_plural': 'Formula Variables'},
        ),
        migrations.AddField(
            model_name='formula',
            name='category',
            field=models.CharField(choices=[('renewable', 'Renewable Energy'), ('verbrauch', 'Energy Consumption'), ('landuse', 'Land Use'), ('bilanz', 'Energy Balance'), ('other', 'Other')], default='renewable', help_text='Category for organizing formulas', max_length=50),
        ),
        migrations.AddField(
            model_name='formula',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive formulas are ignored by calculation engine'),
        ),
        migrations.AddField(
            model_name='formula',
            name='is_fixed',
            field=models.BooleanField(default=False, help_text='True if this represents a fixed value, False if calculated'),
        ),
        migrations.AddField(
            model_name='formula',
            name='last_validated',
            field=models.DateTimeField(blank=True, help_text='Last time formula was validated', null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for developers'),
        ),
        migrations.AddField(
            model_name='formula',
            name='validation_message',
            field=models.TextField(blank=True, help_text='Result of last validation check'),
        ),
        migrations.AddField(
            model_name='formula',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('warning', 'Valid with Warnings')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='formula',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for tracking changes'),
        ),
        migrations.AddField(
            model_name='formulavariable',
            name='is_required',
            field=models.BooleanField(default=True, help_text='If True, formula fails if this variable cannot be resolved'),
        ),
        migrations.AddField(
            model_name='formulavariable',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this variable'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable description of what this formula calculates'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='expression',
            field=models.TextField(help_text="Formula expression (e.g., 'LandUse_1.1 * 1.1.2.1 / 100')"),
        ),
        migrations.AlterField(
            model_name='formula',
            name='key',
            field=models.CharField(help_text="Unique identifier (e.g., '1.1.2.1.2')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='formulavariable',
            name='source_type',
            field=models.CharField(choices=[('landuse_status', 'LandUse status_ha'), ('landuse_target', 'LandUse target_ha'), ('renewable_status', 'RenewableData status_value'), ('renewable_target', 'RenewableData target_value'), ('verbrauch_status', 'VerbrauchData status'), ('verbrauch_ziel', 'VerbrauchData ziel'), ('literal', 'Literal number')], help_text='Type of data source', max_length=30),
        ),
        migrations.AlterField(
            model_name='formulavariable',
            name='variable_name',
            field=models.CharField(help_text='Variable name used in formula expression', max_length=50),
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['category', 'is_active'], name='simulator_f_categor_aca73d_idx'),
        ),
        migrations.AddIndex(
            model_name='formula',
            index=models.Index(fields=['key'], name='simulator_f_key_d1fc4a_idx'),
        ),
    ]
